---
title: "Régressions linéaires avec le jeu de données artificiel anscombe"
author: "___"
date: "___"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R
```

# Visualisation

<!--% Importez le jeu de données `anscombe` depuis le package {datasets} en utilisant la fonction `read()`. --> 

```{r import}
anscombe <- read("___", package = "___")
```

<!--% Réalisez un graphique pour chacune des paires xi - yi (y1 ~ x1, y2 ~ x2, ...) et assemblez-les sur une même figure (présentation des graphiques sur deux lignes et deux colonnes). -->
   
```{r plot}

```
   
<!--% Calculez les coefficients de corrélation pour chaque pairte de variables. -->

```{r corr}

```

# Analyses 

## y1 ~ x1

<!--% Réalisez une régression linéaire, analysez et commentez, en maximum 6 phrases vos résultats. -->

```{r reg1}

```

<!--% Analysez les résidus en utilisant 3 des graphiques vus au cours. Commentez chacun de ceux-ci en maximum 3 phrases. -->

```{r reg1_plot1}

```

```{r reg1_plot2}

```

```{r reg1_plot3}

```

## y2 ~ x2

<!--% Réalisez une régression linéaire, analysez et commentez, en maximum 6 phrases vos résultats. -->

```{r reg2}

```

<!--% Analysez les résidus en utilisant 3 des graphiques vus au cours. Commentez chacun de ceux-ci en maximum 3 phrases. -->

```{r reg2_plot1}

```

```{r reg2_plot2}

```

```{r reg2_plot3}

```

## y3 ~ x3

<!--% Réalisez une régression linéaire, analysez et commentez, en maximum 6 phrases vos résultats. -->

```{r reg3}

```

<!--% Analysez les résidus en utilisant 3 des graphiques vus au cours. Commentez chacun de ceux-ci en maximum 3 phrases. -->

```{r reg3_plot1}

```

```{r reg3_plot2}

```

```{r reg3_plot3}

```

## y4 ~ x4

<!--% Réalisez une régression linéaire, analysez et commentez, en maximum 6 phrases vos résultats. -->

```{r reg4}

```

<!--% Analysez les résidus en utilisant 3 des graphiques vus au cours. Commentez chacun de ceux-ci en maximum 3 phrases. -->

```{r reg4_plot1}

```

```{r reg4_plot2}

```

```{r reg4_plot3}

```

# Conclusion

<!--% En 6 phrases maximum, faites une conclusion globale de vos analyses. -->

